service: ${env:APP_NAME}
variablesResolutionMode: 20210326

frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-plugin-canary-deployments
  - serverless-plugin-resource-tagging

provider:
  name: aws
  region: ${env:AWS_REGION}
  lambdaHashingVersion: 20201221
  environment: ${ssm:/aws/reference/secretsmanager/${env:SECRET_NAME}}
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket: ${env:LAMBDA_DEPLOYMENT_BUCKET}
  deploymentPrefix: ${self:service}
  stackTags:
    App: ${env:APP_NAME}
    Env: ${env:ENVIRONMENT_NAME}

functions:
  app:
    handler: ${env:LAMBDA_HANDLER}
    name: ${self:service}
    runtime: ${env:LAMBDA_RUNTIME}
    memorySize: ${env:LAMBDA_MEMORY_SIZE}
    timeout: ${env:LAMBDA_TIMEOUT}
    role: arn:aws:iam::${env:ACCOUNT_ID}:role/LambdaExecutionRole-${self:service}-${env:ENVIRONMENT_NAME}
    vpc:
      securityGroupIds:
        - ${env:LAMBDA_SECURITY_GROUP_ID}
      subnetIds:
        - ${env:SUBNET_ID_0}
        - ${env:SUBNET_ID_1}
